Python3: Fix bytes-like object error for v2v
Fix below TypeError for virt-v2v

Traceback (most recent call last):
File "/root/Documents/tp-libvirt/v2v/tests/src/v2v_options.py", line 721, in run
check_result(cmd, cmd_result, status_error)
File "/root/Documents/tp-libvirt/v2v/tests/src/v2v_options.py", line 485, in check_result
log_check = utils_v2v.check_log(params, output)
File "/root/Documents/avocado-vt/virttest/utils_v2v.py", line 795, in check_log
if _check_log(msg_list, expect=expect):
File "/root/Documents/avocado-vt/virttest/utils_v2v.py", line 776, in _check_log
search = re.search(compiled_pattern, log)
File "/usr/lib64/python3.6/re.py", line 182, in search
return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object

Signed-off-by: xiaodwan <xiaodwan@redhat.com>