unattended_install: fix bug of copying iso image to local_dir
Now, the iso images are placed in `data_dir` of avocado-vt. However,
the code of copying to `local_dir` finds these images in `test.bindir`,
which is `root_dir` of avocado-vt, then the following error would be
reported:

  IOError: [Errno 2] No such file or directory:
  '/usr/share/avocado-plugins-vt/isos/linux/RHEL7.3-Server-x86_64.iso'

This patch is going to fix the above issue.

Signed-off-by: Xu Han <xuhan@redhat.com>