qemu_vm: Fix bug of migration with qemu 2.10
Qemu 2.10 introduced image file locking feature which would cause
the following automation error during migration.

    QMPCmdError: QMP command 'cont' failed (arguments:
    None, error message: {u'class': u'GenericError',
    u'desc': u'Failed to get "write" lock'})

This patch will fix this problem by not sending `cont` to the
destination before migration started.

Signed-off-by: Xu Han <xuhan@redhat.com>