Fixup:Missing args of ShellError
To fix TypeError: __init__() missing 2 required positional arguments:
'cmd' and 'output'

Signed-off-by: Haijiao Zhao <haizhao@redhat.com>