utils_misc: Fix function name scope typos
There are two function references in a latest patch that mistaken
referred class functions as module functions, thus leading several
test cases failed with:

```
NameError: global name 'get_all_node_meminfo' is not defined
```

Signed-off-by: Hao Liu <hliu@redhat.com>