Hotfix for the RuntimeError during Postprocess
The following failure could be emitted during `Postprocess`:

  RuntimeError: Failures occurred while postprocess:

  Postprocess: 'NoneType' object has no attribute 'cleanup_daemons'

it is introduced by commit 0148461, and because a qemu VM instance are
being `postprocess` without called `create` at its lifetime.

Signed-off-by: Xu Han <xuhan@redhat.com>