remote: Fix typo in regex to avoid failure
In commit f5ccf3da, the regex introduced is not valid and has an asterisk
at the beginning of it. It will cause following failure when running many
cases using this function:
```
    error: nothing to repeat
```

Signed-off-by: Hao Liu <hliu@redhat.com>