virttest: Add named GPIOs support
qemu commit a5f5429 introduced named GPIOs. Some qemu devices(say hpet)
present multiple gpio-in(s) or gpio-out(s) with different string keys
in qtree information. In this case, It causes device_option_check test
failure because it doesn't recognize the string keys, Example:

......
(monitor hmp1) Response to 'info qtree'
(monitor hmp1)    bus: main-system-bus
(monitor hmp1)      type System
(monitor hmp1)      dev: hpet, id ""
(monitor hmp1)        gpio-in "" 2
(monitor hmp1)        gpio-out "" 1
(monitor hmp1)        gpio-out "sysbus-irq" 32
......
ValueError: Property gpio-out = "" 1, not rewriting with "sysbus-irq" 32
......

This patch adds the named GPIOs support to fix this issue.

Signed-off-by: Lin Ma <lma@suse.com>