Fixup: type cast version info values to string
Json read of the version info file fails sometimes when we
have version string with spaces, and causes below failure,

net.sf.json.JSONException: Unquotted string 'u'3.1.50 (v2.8.0-rc0-17028-g3e78ecb378-dirty)''

let's type cast to string to avoid such cases.

Signed-off-by: Satheesh Rajendran <sathnaga@linux.vnet.ibm.com>