utils_test: python3 doesn't support iteritems()
fix to adopt python3 as it doesn't support iteritems() instead
use items().

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'dict' object has no attribute 'iteritems'

Signed-off-by: Balamuruhan S <bala24@linux.ibm.com>