Fixup: add default transfer_timeout to avoid test failure
transfer_timeout does not have a default value set in
any of global config, so if not set explicitly will
lead to below error, as it got typecasted
to int while accessing.

 TypeError: int() argument must be a string or a number, not 'NoneType'

This patch avoids it by setting the default value.

Signed-off-by: Satheesh Rajendran <sathnaga@linux.vnet.ibm.com>