Workaround ImportError
A circular import problem occurred after commit daf3fa6.

    | ImportError('cannot import name qdevices',)

This patch help workaround this issue for python 2.7, and the
repair will be coming soon.

Signed-off-by: Xu Han <xuhan@redhat.com>