Fix get iface error
resolve the get method as ip route may display like this

default via 10.73.11.254 dev eno1
default via 10.73.11.254 dev eno1 proto dhcp metric 100

which cause error from "addr = netifaces.ifaddresses(ifname).get(ver)" like
ValueError: You must specify a valid interface name.

Signed-off-by: Kyla Zhang <weizhan@redhat.com>