virttest.remote: Escape the src/dst paths when using scp
Usually "scp $src $dst" works, but when special characters like `;` are
supplied, everything breaks due to bash considering further chars as
another command.

This fixes an issue where (not just) "hwclock" test is trying to copy
files from guest to host's datadir, which might (in case variants are
used) contain `;`:

    scp -v -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PreferredAuthentications=password -r  -P 22 root@\[192.168.122.82\]:/var/tmp/avocado_iIosLt/results.tgz /root/avocado/job-results/job-2018-03-06T18.22-0d1175e/test-results/04-io-github-autotest-qemu.autotest.hwclock;-e630/data/guest_autotest_results1
    SCPTransferFailedError: SCP transfer failed    (status: 127,    output: u'\ndebug1: Authentication succeeded (password).\nAuthenticated to 192.168.122.82 ([192.168.122.82]:22).\ndebug1: channel 0: new [client-session]\ndebug1: Requesting no-more-sessions@openssh.com\ndebug1: Entering interactive session.\ndebug1: pledge: network\ndebug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0\ndebug1: Sending environment.\ndebug1: Sending env LANG = C\ndebug1: Sending command: scp -v -r -f /var/tmp/avocado_iIosLt/results.tgz\nSending file modes: C0644 45507 results.tgz\nSink: C0644 45507 results.tgz\nresults.tgz                                     0%    0     0.0KB/s   --:-- ETAresults.tgz                                   100%   44KB   4.6MB/s   00:00    \ndebug1: client_input_channel_req: channel 0 rtype exit-status reply 0\ndebug1: client_input_channel_req: channel 0 rtype eow@openssh.com reply 0\ndebug1: channel 0: free: client-session, nchannels 1\ndebug1: fd 0 clearing O_NONBLOCK\ndebug1: fd 1 clearing O_NONBLOCK\nTransferred: sent 2016, received 48084 bytes, in 0.2 seconds\nBytes per second: sent 9286.6, received 221495.4\ndebug1: Exit status 0\n/tmp/aexpect_acoPFj3Y/aexpect-U4zX5f.sh: line 1: -e630/data/guest_autotest_results1: No such file or directory\n')

With `pipes.quote` it works well, although it might break some tests
where manual escapes were added (I'm not aware of any, but it might
happen). Anyway I believe users should expect the `scp_from_remote`
function to escape the inputs.

Signed-off-by: Lukáš Doktor <ldoktor@redhat.com>