Fix TypeError for IOTune and Encryption class in disk xml.
The current implementation caused the Exception:
TypeError: super(type, obj): obj must be an instance or subtype of type
It should use self.__class__ as the type parameter in this function.