setup.py: pin urllib3 to a compatible version on Python 2
Urllib3, on commit f80ff34bffb2018528ccd2ccf82e533d321f2af8, added a
syntax that is valid with pip, but that setup.py doesn't agree with:

   Running urllib3-1.25.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-DIrJy8/urllib3-1.25.3/egg-dist-tmp-HWbQS7
   error: Setup script exited with error in urllib3 setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.

Let's pin to a version before that change was introduced.

Reference: https://github.com/urllib3/urllib3/commit/f80ff34bffb2018528ccd2ccf82e533d321f2af8
Signed-off-by: Cleber Rosa <crosa@redhat.com>