Fix inappropriately captured unavailable vm monitor
The responsive monitor checks only expect monitor errors and miss
an error about unavailable file descriptor like:

Reproduced traceback from: /usr/lib/python3.8/site-packages/avocado_vt/test.py:461
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/virttest/error_context.py", line 135, in new_fn
    return fn(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/virttest/env_process.py", line 1870, in postprocess
    postprocess_vm_off_hook(test, params, env)  # pylint: disable=E1102
  File "/usr/lib/python3.8/site-packages/avocado_i2n/cmd_parser.py", line 233, in wrapper
    fn(params, env)
  File "/usr/lib/python3.8/site-packages/avocado_i2n/states/setup.py", line 525, in set_state
    state_exists = _state_check_chain("set", env, vm_name, vm_params, image_name, image_params)
  File "/usr/lib/python3.8/site-packages/avocado_i2n/states/setup.py", line 290, in _state_check_chain
    state_exists = check_state(image_params, env)
  File "/usr/lib/python3.8/site-packages/avocado_i2n/states/setup.py", line 383, in check_state
    boot_exists = on_backend.check_root(image_params, vm)
  File "/usr/lib/python3.8/site-packages/avocado_i2n/states/setup.py", line 218, in check_root
    condition = vm is not None and vm.is_alive()
  File "/usr/lib/python3.8/site-packages/virttest/qemu_vm.py", line 248, in is_alive
    self.catch_monitor.is_responsive())
  File "/usr/lib/python3.8/site-packages/virttest/qemu_monitor.py", line 493, in is_responsive
    self.verify_responsive()
  File "/usr/lib/python3.8/site-packages/virttest/qemu_monitor.py", line 951, in verify_responsive
    self.cmd("info status", debug=False)
  File "/usr/lib/python3.8/site-packages/virttest/qemu_monitor.py", line 905, in cmd
    self._recvall()
  File "/usr/lib/python3.8/site-packages/virttest/qemu_monitor.py", line 395, in _recvall
    while self._data_available():
  File "/usr/lib/python3.8/site-packages/virttest/qemu_monitor.py", line 384, in _data_available
    return bool(select.select([self._socket], [], [], timeout)[0])
ValueError: file descriptor cannot be a negative integer (-1)

Signed-off-by: Plamen Dimitrov <plamen.dimitrov@intra2net.com>