env_process: virsh requires hostname to resolved with IP for migration
Adopt migration setup to map hostname and ipaddress of the hosts in
source and target for virsh to resolve and migrate without error.

virsh throws error if it fails to resolve the IP during migration

```
error: Unable to resolve address 'ltc-fire4' service '49152': Name or service not known`
```

Signed-off-by: Balamuruhan S <bala24@linux.vnet.ibm.com>