qemu_vm: fix vhostfd AttributeError
Got the following error since the code did not do a check on the
value of the `nic.vhostfd` var (and also the `nic.tapfds` var).

> File "virttest/qemu_vm.py", line 3656, in create
>     "vhostfd": nic.vhostfds.split(":")[0],
>                ^^^^^^^^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'split'

This patch fixes the attribute error.

Signed-off-by: Xu Han <xuhan@redhat.com>