avocado-plugins-vt.spec: fix Python 2 (only) builds
Because of the conditional around the configuration dir
copy, on Python 2 (only) builds, we'd end up without a
configuration, resulting in:

   error: Directory not found: /builddir/build/BUILDROOT/avocado-plugins-vt-70.0-3.20190814git44b36d00.el7.ppc64le/etc/avocado

Signed-off-by: Cleber Rosa <crosa@redhat.com>