Fixup: Improper initialization of vmcpu_xml
In some scenarios, we would hit below issue due to vmcpu_xml
is not initialized in proper place, this patch tries to fix it.

UnboundLocalError: local variable 'vmcpu_xml' referenced before assignment

Reported-by: Junxiang Li <junli@redhat.com>
Signed-off-by: Satheesh Rajendran <sathnaga@linux.vnet.ibm.com>