NumaInfo: Fix 'NoneType' object has no attribute 'groups' error
The content of /sys/devices/system/node/node*/meminfo may have space
after the last '\n', and will cause AttributeError.
e.g.
>>> file = '/sys/devices/system/node/node1/meminfo'
>>> data = os.popen('cat %s' %file).read()
>>> data.split('\n')[-1]
''
>>> data.strip().split('\n')[-1]
'Node 1 HugePages_Surp:      0'

Signed-off-by: Yanan Fu <yfu@redhat.com>