qcontainer: Fix AttributeError: 'NoneType' object has no attribute
On commit 91fe444, there was a mistake that raised AttributeError:
'NoneType' object has no attribute 'startswith' in the scenario where
the filename was None.

Signed-off-by: Yongxue Hong <yhong@redhat.com>